name: Greg Elizondo
markdown: redcarpet
pygments: true
gitub: www.github.com/gregelizondo
about: MBA, marketer, Rubyist in training
urls:
    - text: github
      url: https://github.com/gregelizondo
    - text: twitter
      url: https://twitter.com/gregelizondo
